# Generated by Django 5.0.3 on 2024-03-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_add_slug_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip_code",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
